artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rj202/End-to-End-Machine-Learning-Project-with-ML-Flow/raw/refs/heads/main/winequality-red.zip #upload the zip file in github repository and right click the file for copy the path.
  local_data_file: artifacts/data_ingestion/data.zip
 # save the data in this local folder 
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv # read data from the csv of the unzip folder of data ingestion
  STATUS_FILE: artifacts/data_validation/status.txt # the status file (true or false) shows the data type.

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json